name: shopperz
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+13

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  dotted_line: ^3.2.2
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.4.1
  shimmer: ^3.0.0
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  country_state_city_picker: ^1.2.8
  dropdown_search: ^6.0.1
  csc_picker: ^0.2.7
  country_code_picker: ^3.0.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0
  printing: ^5.12.0
  flutter_html:
  youtube_player_flutter: ^9.1.0
  firebase_messaging: ^15.1.2
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.0.0
  flutter_inappwebview: ^6.1.0+1
  win32: ^5.5.3
  archive: ^4.0.5
  flutter_spinkit: ^5.2.2
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/product-details/
