Map<String, String> arabic = {
  "CATEGORIES": "الفئات",
  "TRENDY_COLLECTIONS": "المجموعات الرائجة",
  "FLASH_SALE": "تخفيضات سريعة",
  "SEE_ALL": "عرض الكل",
  "NEW": "جديد",
  "HOME": "الرئيسية",
  "CATEGORY": "الفئة",
  "WISHLIST": "قائمة الرغبات",
  "PROFILE": "الملف الشخصي",
  "MEN": "رجال",
  "WOMEN": "نساء",
  "KIDS": "الأطفال",
  "SPORTS": "الرياضة",
  "SALE_AND_OFFER": "عروض وتخفيضات",
  "SING_IN_TO_SEE_YOUR_INFO": "تسجيل الدخول لمشاهدة معلوماتك",
  "Sing In": "تسجيل الدخول",
  "Sign in to continue shopping": "سجّل الدخول للمتابعة بالتسوق",
  "Password": "كلمة المرور",
  "Forgot Password": "نسيت كلمة المرور",
  "Don't have an account?": "لا تملك حسابًا؟",
  "Remember me": "تذكرني",
  "Sign Up": "إنشاء حساب",
  "Email": "البريد الإلكتروني",
  "Phone": "الهاتف",
  "*Use Phone Instead": "*استخدم الهاتف بدلًا من ذلك",
  "*Use Email Instead": "*استخدم البريد الإلكتروني بدلًا من ذلك",
  "Name": "الاسم",
  "Already have an account?": "هل لديك حساب بالفعل؟",
  "Welcome Back": "مرحبًا بعودتك",
  "Welcome Back, ": "مرحبًا بعودتك، ",
  "MY_ACCOUNT": "حسابي",
  "ORDER_HISTORY": "سجل الطلبات",
  "RETURN_ORDERS": "إرجاع الطلبات",
  "CHANGE_PASSWORD": "تغيير كلمة المرور",
  "EDIT_PROFILE": "تعديل الملف الشخصي",
  "ADDRESSES": "العنوان",
  "Terms & Conditions": "الشروط والأحكام",
  "Privacy Policy": "سياسة الخصوصية",
  "CONTACT_US": "اتصل بنا",
  "About Us": "معلومات عنا",
  "LOGOUT": "تسجيل الخروج",
  "Cookies Policy": "سياسة الكوكيز",
  "Size Charts": "مخططات المقاسات",
  "Shipping": "الشحن",
  "Return & Exchange": "الإرجاع والتبديل",
  "Help": "مساعدة",
  "TOTAL_ORDERS": "إجمالي الطلبات",
  "TOTAL_COMPLETED": "اكتملت بالكامل",
  "TOTAL_RETURNED": "إجمالي المرتجعات",
  "WALLET_BALANCE": "رصيد المحفظة",
  "CHANGE_LANGUAGE": "تغيير اللغة",
  "CHOOSE_SIZE": "اختر المقاس:",
  "CHOOSE_COLOR": "اختر اللون:",
  "QUANTITY": "الكمية:",
  "FAVORITE": "مفضل",
  "ADD_TO_CART": "أضف إلى السلة",
  "SHIPPING_AND_RETURN": "الشحن والإرجاع",
  "REVIEW": "التقييمات",
  "DETAILS": "التفاصيل",
  "PRODUCT_DTAILS": "تفاصيل المنتج",
  "RELATED_PRODUCTS": "منتجات ذات صلة",
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": "تم حفظ صورة الملف الشخصي بنجاح",
  "SUCCESS": "نجاح",
  "ERROR": "خطأ",
  "Press back again to exit.": "اضغط مرة أخرى للعودة للخروج.",
  "Home": "الرئيسية",
  "Category": "الفئة",
  "Wishlist": "قائمة الرغبات",
  "Profile": "الملف الشخصي",
  "Address": "العنوان",
  "Add New Address": "إضافة عنوان جديد",
  "Full Name": "الاسم الكامل",
  "Zip Code": "الرمز البريدي",
  "Street Address": "عنوان الشارع",
  "Add Address": "إضافة عنوان",
  "Cancel": "إلغاء",
  "Update Address": "تحديث العنوان",
  "Are you sure you want to delete?": "هل أنت متأكد أنك تريد الحذف؟",
  "Delete": "حذف",
  "Change Password": "تغيير كلمة المرور",
  "Old Password": "كلمة المرور القديمة",
  "PLEASE_TYPE_OLD_PASSWORD": "يرجى إدخال كلمة المرور القديمة",
  "PLEASE_TYPE_NEW_PASSWORD": "يرجى إدخال كلمة المرور الجديدة",
  "New Password": "كلمة المرور الجديدة",
  "Confirm Password": "تأكيد كلمة المرور",
  "PLEASE_TYPE_CONFIRM_PASSWORD": "يرجى تأكيد كلمة المرور",
  "PASSWORD_NOT_MATCHED": "كلمتا المرور غير متطابقتين",
  "Save Changes": "حفظ التغييرات",
  "Edit Profile": "تعديل الملف الشخصي",
  "PLEASE_TYPE_Name": "يرجى إدخال الاسم الكامل",
  "PLEASE_TYPE_EMAIL": "يرجى إدخال البريد الإلكتروني",
  "PLEASE_TYPE_PHONE_NUMBER": "يرجى إدخال رقم الهاتف",
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": "يجب أن تكون الصورة أقل من 2 ميغابايت",
  "SOMETHING_WRONG": "حدث خطأ ما",
  "PROFILE_UPDATE_SUCCESSFULLY": "تم تحديث الملف الشخصي بنجاح",
  "PASSWORD_UPDATE_SUCCESSFULLY": "تم تغيير كلمة المرور بنجاح",
  "PLEASE_ENTER_VALID_INPUT": "يرجى إدخال قيمة صالحة",
  "Verify Email": "تحقق من البريد الإلكتروني",
  "Verify Number": "تحقق من الرقم",
  "Enter OTP": "أدخل الرمز",
  "If you didn't receive a code!": "إذا لم يصلك رمز!",
  " Resend": " إعادة الإرسال",
  "Verify": "تحقق",
  "Back to sign in": "العودة لتسجيل الدخول",
  "Get OTP": "احصل على رمز",
  "Reset Password": "إعادة تعيين كلمة المرور",
  "Password Not Matched": "كلمتا المرور غير متطابقتين",
  "Submit": "إرسال",
  "Popular Brands": "الماركات الشهيرة",
  "Explore All Products": "استعراض كل المنتجات",
  "Empty Wishlist": "قائمة رغبات فارغة",
  "Search": "بحث",
  "Product added to cart": "تم إضافة المنتج إلى السلة",
  "Product Details": "تفاصيل المنتج",
  "No Review": "لا توجد تقييمات",
  "No Shipping & Return Policy": "لا توجد سياسة شحن وإرجاع",
  "VIDEOS": "فيديوهات",
  "Product Videos": "فيديوهات المنتج",
  "Shipping & Return": "الشحن والإرجاع",
  "Product Reviews": "تقييمات المنتج",
  "Order Details": "تفاصيل الطلب",
  "Thank You": "شكرًا لك",
  "Your Order status is as follows": "حالة طلبك كما يلي",
  "Order ID: ": "رقم الطلب: ",
  "Order Canceled": "تم إلغاء الطلب",
  "Order Rejected": "تم رفض الطلب",
  "Order ID:": "رقم الطلب:",
  "Order Date:": "تاريخ الطلب:",
  "Order Status:": "حالة الطلب:",
  "Payment Status:": "حالة الدفع:",
  "Payment Type:": "طريقة الدفع:",
  "Pending": "قيد الانتظار",
  "Confirmed": "تم التأكيد",
  "On The Way": "في الطريق",
  "Delivered": "تم التوصيل",
  "Cenceled": "أُلغي",
  "Rejected": "مرفوض",
  "Paid": "مدفوع",
  "Unpaid": "غير مدفوع",
  "Name:": "الاسم:",
  "Phone:": "الهاتف:",
  "Email:": "البريد الإلكتروني:",
  "Outlet Address:": "عنوان المتجر:",
  "Shipping Address:": "عنوان الشحن:",
  "Billing Address:": "عنوان الفوترة:",
  "Order Summary": "ملخص الطلب",
  "Subtotal": "المجموع الفرعي",
  "Tax": "الضريبة",
  "Shipping Charge": "رسوم الشحن",
  "Discount": "الخصم",
  "Download Receipt": "تحميل الإيصال",
  "Return Request": "طلب الإرجاع",
  "Cancel Order": "إلغاء الطلب",
  "Tel:": "تلفون:",
  "Order#": "رقم الطلب#",
  "Qty": "الكمية",
  "Item Description": "وصف المنتج",
  "Price": "السعر",
  "Total": "الإجمالي",
  "Order Type": "نوع الطلب",
  "Order Date Time": "تاريخ ووقت الطلب",
  "Delivery": "توصيل",
  "Pickup": "استلام",
  "POS": "نقاط البيع",
  "Customer": "العميل",
  "Powered by": "تشغيل بواسطة",
  "Print Invoice": "طباعة الفاتورة",
  "Edit Review": "تعديل التقييم",
  "Your Review": "تقييمك",
  "Review Details": "تفاصيل التقييم",
  "Please write review details": "يرجى كتابة تفاصيل التقييم",
  "Upload Images": "رفع صور",
  "Add Image": "إضافة صورة",
  "Submit Review": "إرسال التقييم",
  "Info: ": "معلومة: ",
  "Product": "المنتج",
  "Delivery Status: ": "حالة التوصيل: ",
  "Payment Status: ": "حالة الدفع: ",
  "Total: ": "الإجمالي: ",
  "Qty:": "الكمية:",
  "Write Review": "اكتب تقييمًا",
  "Price: ": "السعر: ",
  "Return Status: ": "حالة الإرجاع: ",
  "Accepted": "مقبول",
  "Return Order Details": "تفاصيل طلب الإرجاع",
  "Return Reason": "سبب الإرجاع",
  "Return Note": "ملاحظة الإرجاع",
  "Attachment": "مرفق",
  "Return Response": "رد الإرجاع",
  "Request Return": "طلب إرجاع",
  "Please select return reason": "يرجى اختيار سبب الإرجاع",
  "Please write return note": "يرجى كتابة ملاحظة الإرجاع",
  "Please select an item": "يرجى اختيار منتج",
  "Order Canceled Successfully!": "تم إلغاء الطلب بنجاح!",
  "Return request submitted successfully!": "تم إرسال طلب الإرجاع بنجاح!",
  "Return request not submitted": "لم يتم إرسال طلب الإرجاع",
  "Review submitted successfully!": "تم إرسال التقييم بنجاح!",
  "Review not submitted": "لم يتم إرسال التقييم",
  "Review Updated successfully!": "تم تحديث التقييم بنجاح!",
  "Address Added Successfully!": "تم إضافة العنوان بنجاح!",
  "ADDRESS_UPDATED_SUCCESSFULLY": "تم تحديث العنوان بنجاح!",
  "ADDRESS_DELETED_SUCCESSFULLY": "تم حذف العنوان بنجاح!",
  "Shipping Information": "معلومات الشحن",
  "Pick Up": "استلام",
  "Shipping Address": "عنوان الشحن",
  "Edit": "تعديل",
  "Add": "إضافة",
  "Save shipping address as a billing address.":
      "احفظ عنوان الشحن كعنوان فوترة.",
  "Apply Promo, Coupon or Voucher": "تطبيق كود ترويجي أو قسيمة",
  "Coupon Applied": "تم تطبيق القسيمة",
  "Get discount with your order": "احصل على خصم على طلبك",
  "You saved": "لقد وفّرت",
  "Shipping & billing addresses are required.":
      "عنوانين الشحن والفوترة مطلوبان.",
  "Outlet is required.": "المتجر مطلوب.",
  "Save & Pay": "حفظ ودفع",
  "Order": "طلب",
  "On the": "في الطريق",
  "Way": "على",
  "Stock is over": "المخزون نفد",
  "Shopping Cart": "سلة التسوق",
  "Your cart is empty": "سلتك فارغة! ابدأ التسوق الآن!",
  "Proceed to Checkout": "المتابعة إلى الدفع",
  "Shipping, Taxes & Discount Calculate at Checkout":
      "يتم حساب الشحن والضرائب والخصم عند الدفع",
  "Remove": "إزالة",
  "Enter Code": "أدخل كود",
  "Please enter a valid coupon": "يرجى إدخال قسيمة صحيحة",
  "Promo, Coupon or Voucher": "رمز ترويجي أو قسيمة",
  "Apply": "تطبيق",
  "Coupon & Vouchers for you": "قسائم مخصصة لك",
  "Filter & Sorting": "تصفية وفرز",
  "Product Type": "نوع المنتج",
  "Size": "المقاس",
  "Color": "اللون",
  "Brands": "الماركات",
  "Sort By": "ترتيب حسب",
  "Newest": "الأحدث",
  "Price Low To High": "السعر من الأقل للأعلى",
  "Price High To Low": "السعر من الأعلى للأقل",
  "Top Rated": "الأعلى تقييمًا",
  "See All": "عرض الكل",
  "Payment Information": "معلومات الدفع",
  "Select Payment Method": "اختر طريقة الدفع",
  "Confirm Order": "تأكيد الطلب",
  "Products Found": "المنتجات المتوفرة",
  "Flash Sale": "تخفيضات سريعة",
  "New": "جديد",
  "Reviews": "التقييمات",
  " Products Found": " المنتجات المتوفرة",
  "Validation Error.": "خطأ في الإدخال.",
  "Credentials errors.": "خطأ في بيانات الاعتماد.",
  "Invalid credentials or you are blocked":
      "بيانات الدخول غير صحيحة أو تم حظرك",
  "Role errors.": "خطأ في الصلاحيات.",
  "Role does not exist.": "الصلاحية غير موجودة.",
  "Login Successfully.": "تم تسجيل الدخول بنجاح.",
  "Logged Out Successfully.": "تم تسجيل الخروج بنجاح.",
  "Invalid Api Key.": "مفتاح API غير صالح.",
  "User not match.": "المستخدم غير مطابق.",
  "Something wrong.": "حدث خطأ ما.",
  "The permission is denied.": "تم رفض الإذن.",
  "Product not match.": "المنتج غير مطابق.",
  "The product already added in another offer. When the offer is end then you can add this item again.":
      "المنتج مضاف بالفعل في عرض آخر. عند انتهاء العرض يمكنك إضافته مجددًا.",
  "The minimum order amount is ": "الحد الأدنى للطلب هو ",
  "The coupon time is expired": "انتهت صلاحية القسيمة",
  "The coupon does not exist": "القسيمة غير موجودة",
  "The code is invalid.": "الكود غير صالح.",
  "The code is expired.": "الكود منتهي الصلاحية.",
  "Now you can reset your password.": "يمكنك الآن إعادة تعيين كلمة المرور.",
  "Please check your email for the code.": "يرجى التحقق من بريدك للكود.",
  "Please check your phone for the code.": "يرجى التحقق من هاتفك للكود.",
  "The token created fail.": "فشل إنشاء التوكن.",
  "This email does not exist.": "هذا البريد غير موجود.",
  "This phone does not exist.": "هذا الرقم غير موجود.",
  "This User does not exist.": "هذا المستخدم غير موجود.",
  "This phone already exist.": "هذا الرقم موجود بالفعل.",
  "The OTP verify is successfully.": "تم التحقق من الكود بنجاح.",
  "The User verify is successfully.": "تم التحقق من المستخدم بنجاح.",
  "Register Successfully.": "تم إنشاء الحساب بنجاح.",
  "Your password reset Successfully.": "تم إعادة تعيين كلمة المرور بنجاح.",
  "Select your payment method": "اختر طريقة الدفع",
  "Your payment has been successfully processed": "تمت معالجة الدفع بنجاح",
  "The payment is canceled": "تم إلغاء الدفع",
  "The payment gateway is disable": "بوابة الدفع معطّلة",
  "The token saved successfully.": "تم حفظ التوكن بنجاح.",
  "The token is invalid.": "التوكن غير صالح.",
  "The order already accepted.": "تم قبول الطلب مسبقًا.",
  "The order already confirmed.": "تم تأكيد الطلب مسبقًا.",
  "This feature is disabled for the demo.": "هذه الميزة معطّلة للعرض التجريبي.",
  "Time slots already exist.": "الفترات الزمنية موجودة مسبقًا.",
  "This attribute is invalid. Create attribute or attribute option.":
      "هذه الخاصية غير صالحة. أنشئ خاصية أو خيار خاصية.",
  "This price amount provide invalid.": "المبلغ غير صالح.",
  "This product attribute id provide invalid.": "معرّف خاصية المنتج غير صالح.",
  "This product attribute option id provide invalid.":
      "معرّف خيار الخاصية غير صالح.",
  "The sku has already been taken.": "رمز المخزون (SKU) مأخوذ مسبقًا.",
  "Cannot remove this resource permanently. It is related with another resource.":
      "لا يمكن حذف هذا المورد نهائيًا، مرتبط بمورد آخر.",
  "The sku field is required.": "حقل رمز المخزون مطلوب.",
  "The email or phone field is required.":
      "حقل البريد الإلكتروني أو الهاتف مطلوب.",
  "The Country has already been taken.": "الدولة مأخوذة مسبقًا.",
  "The tax field is required for all products.":
      "حقل الضريبة مطلوب لجميع المنتجات.",
  "The quantity field is required for all products.":
      "حقل الكمية مطلوب لجميع المنتجات.",
  "The product filed is required.": "حقل المنتج مطلوب.",
  "The unit cost filed is required for all products.":
      "حقل تكلفة الوحدة مطلوب لجميع المنتجات.",
  "The total product unit cost is invalid.": "إجمالي تكلفة الوحدة غير صالح.",
  "The supplier is invalid.": "المورد غير صالح.",
  "The status is invalid.": "الحالة غير صالحة.",
  "The Return request already exist.": "طلب الإرجاع موجود بالفعل.",
  "The last outlet can not be delete": "لا يمكن حذف آخر منفذ.",
  "Email Send Successfully.": "تم إرسال البريد الإلكتروني بنجاح.",
  "The amount is invalid.": "المبلغ غير صالح.",
  "Available:": "متوفر:",
  "Piece": "قطعة",
  "Search Results": "نتائج البحث",
  "Order Type:": "نوع الطلب:",
  "Product Description": "وصف المنتج",
  "Outlet": "المنفذ",
  "Enter Valid Email Address": "أدخل بريدًا إلكترونيًا صالحًا",
  "Thank you for your order!": "شكرًا لطلبك!",
  "Your order is confirmed.": "تم تأكيد طلبك.",
  "Go to order details": "الذهاب إلى تفاصيل الطلب",
  "YOUR_PAYMENT_HAS_BEEN_CONFIRMED": "تم تأكيد دفعك",
  "PAYMENT_FAILED": "فشل الدفع",
  "ARE_YOU_SURE_WANT_TO_CLOSE_THIS_PAYMENT_SESSION":
      "هل أنت متأكد من رغبتك في إغلاق جلسة الدفع؟",
  "YES_CLOSE": "نعم",
  "RETRY": "إعادة المحاولة",
  "Please select payment method.": "يرجى اختيار طريقة الدفع.",
  "Billing Address": "عنوان الفوترة",
  "Insufficient balance": "الرصيد غير كافٍ",
  "Most Popular": "الأكثر شعبية",
  "Added to Wishlist": "أُضيف إلى قائمة الرغبات",
  "Removed from Wishlist": "أُزيل من قائمة الرغبات",
  "DELETE_ACCOUNT": "حذف الحساب",
  "COUNTRY": "الدولة",
  "STATE": "المنطقة",
  "CITY": "المدينة",
  "MAXIMUM_PURCHASE_QUANTITY_LIMIT_EXCEEDED": "تم تجاوز الحد الأقصى للكمية",
  "YOU_ALREADY_ADDED_THE_MAXIMUM_QUANTITY": "لقد أضفت الكمية القصوى بالفعل",
  "COUNTRY_IS_REQUIRED": "الدولة مطلوبة",
  "STATE_IS_REQUIRED": "المقاطعة/المنطقة مطلوبة",
  "CITY_IS_REQUIRED": "المدينة مطلوبة",
  "PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS":
      "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
  "PASSWORD_IS_REQUIRED": "كلمة المرور مطلوبة",
  "ENTER_A_VALID_EMAIL": "أدخل بريدًا إلكترونيًا صالحًا",
  "EMAIL_IS_REQUIRED": "البريد الإلكتروني مطلوب",
  "ADDRESS_IS_REQUIRED": "العنوان مطلوب",
  "OTP_IS_REQUIRED": "الكود مطلوب",
  "PHONE_IS_REQUIRED": "الهاتف مطلوب",
  "NAME_IS_REQUIRED": "الاسم مطلوب",
  "FULL_NAME_IS_REQUIRED": "الاسم الكامل مطلوب",
  "ORDER_HISTORY_IS_EMPTY": "سجل الطلبات فارغ!",
  "RETURN_ORDER_IS_EMPTY": "سجل الإرجاع فارغ!",
  "WISHLIST_IS_EMPTY": "قائمة الرغبات فارغة!",
  "CART_IS_EMPTY": "سلتك فارغة! ابدأ التسوق الآن!",
  "NO_PRODUCT_FOUND": "لم يتم العثور على منتجات!",
  "NO_SUB_CATEGORY_FOUND": "لم يتم العثور على فئات فرعية!",
  "INFO": "معلومة",
};
