Map<String, String> bangla = {
  "CATEGORIES": "বিভাগসমূহ",
  "TRENDY_COLLECTIONS": "ট্রেন্ডি কালেকশন",
  "FLASH_SALE": "ফ্ল্যাশ সেল",
  "SEE_ALL": "সব দেখুন",
  "NEW": "নতুন",
  "HOME": "হোম",
  "CATEGORY": "বিভাগ",
  "WISHLIST": "ইচ্ছেতালিকা",
  "PROFILE": "প্রোফাইল",
  "MEN": "পুরুষ",
  "WOMEN": "নারী",
  "KIDS": "শিশু",
  "SPORTS": "খেলাধুলা",
  "SALE_AND_OFFER": "ছাড় এবং অফার",
  "SING_IN_TO_SEE_YOUR_INFO": "তথ্য দেখতে সাইন ইন করুন",
  "Sing In": "সাইন ইন",
  "Sign in to continue shopping": "ক্রয় চালিয়ে যেতে সাইন ইন করুন",
  "Password": "পাসওয়ার্ড",
  "Forgot Password": "পাসওয়ার্ড ভুলে গেছেন",
  "Don't have an account?": "একটি অ্যাকাউন্ট নেই?",
  "Remember me": "আমাকে মনে রাখুন",
  "Sign Up": "সাইন আপ",
  "Email": "ইমেইল",
  "Phone": "ফোন",
  "*Use Phone Instead": "*ফোন ব্যবহার করুন",
  "*Use Email Instead": "*ইমেইল ব্যবহার করুন",
  "Name": "নাম",
  "Already have an account?": "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
  "Welcome Back": "আবার স্বাগতম",
  "MY_ACCOUNT": "আমার অ্যাকাউন্ট",
  "ORDER_HISTORY": "অর্ডার ইতিহাস",
  "RETURN_ORDERS": "রিটার্ন অর্ডার",
  "CHANGE_PASSWORD": "পাসওয়ার্ড পরিবর্তন",
  "EDIT_PROFILE": "প্রোফাইল সম্পাদনা",
  "ADDRESSES": "ঠিকানা",
  "Terms & Conditions": "শর্তাবলী",
  "Privacy Policy": "গোপনীয়তা নীতি",
  "CONTACT_US": "যোগাযোগ করুন",
  "About Us": "আমাদের সম্পর্কে",
  "LOGOUT": "লগআউট",
  "Cookies Policy": "কুকি নীতি",
  "Size Charts": "সাইজ চার্ট",
  "Shipping": "ডেলিভারি",
  "Return & Exchange": "রিটার্ন ও পরিবর্তন",
  "Help": "সাহায্য",
  "TOTAL_ORDERS": "মোট অর্ডার",
  "TOTAL_COMPLETED": "সম্পন্ন অর্ডার",
  "TOTAL_RETURNED": "রিটার্নকৃত অর্ডার",
  "WALLET_BALANCE": "ওয়ালেট ব্যালেন্স",
  "CHANGE_LANGUAGE": "ভাষা পরিবর্তন করুন",
  "CHOOSE_SIZE": "সাইজ নির্বাচন করুন:",
  "CHOOSE_COLOR": "রঙ নির্বাচন করুন:",
  "QUANTITY": "পরিমাণ:",
  "FAVORITE": "প্রিয়",
  "ADD_TO_CART": "কার্টে যোগ করুন",
  "SHIPPING_AND_RETURN": "পণ্য ডেলিভারি ও রিটার্ন",
  "REVIEW": "রিভিউ",
  "DETAILS": "বিস্তারিত",
  "PRODUCT_DTAILS": "পণ্যের বিস্তারিত",
  "RELATED_PRODUCTS": "সংশ্লিষ্ট পণ্য",
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": "প্রোফাইল ছবি সফলভাবে সংরক্ষিত হয়েছে",
  "SUCCESS": "সফল",
  "ERROR": "ত্রুটি",
  "Press back again to exit.": "বের হতে আবার ব্যাক চাপুন।",
  "Home": "হোম",
  "Category": "বিভাগ",
  "Wishlist": "ইচ্ছেতালিকা",
  "Profile": "প্রোফাইল",
  "Address": "ঠিকানা",
  "Add New Address": "নতুন ঠিকানা যোগ করুন",
  "Full Name": "পুরো নাম",
  "Zip Code": "জিপ কোড",
  "Street Address": "রাস্তার ঠিকানা",
  "Add Address": "ঠিকানা যোগ করুন",
  "Cancel": "বাতিল করুন",
  "Update Address": "ঠিকানা আপডেট করুন",
  "Are you sure you want to delete?": "আপনি কি মুছে ফেলতে চান?",
  "Delete": "মুছে ফেলুন",
  "Change Password": "পাসওয়ার্ড পরিবর্তন করুন",
  "Old Password": "পুরাতন পাসওয়ার্ড",
  "PLEASE_TYPE_OLD_PASSWORD": "অনুগ্রহ করে পুরাতন পাসওয়ার্ড লিখুন",
  "PLEASE_TYPE_NEW_PASSWORD": "অনুগ্রহ করে নতুন পাসওয়ার্ড লিখুন",
  "New Password": "নতুন পাসওয়ার্ড",
  "Confirm Password": "পাসওয়ার্ড নিশ্চিত করুন",
  "PLEASE_TYPE_CONFIRM_PASSWORD": "অনুগ্রহ করে নিশ্চিত পাসওয়ার্ড লিখুন",
  "PASSWORD_NOT_MATCHED": "পাসওয়ার্ড মিলছে না",
  "Save Changes": "পরিবর্তন সংরক্ষণ করুন",
  "Edit Profile": "প্রোফাইল সম্পাদনা করুন",
  "PLEASE_TYPE_Name": "অনুগ্রহ করে পুরো নাম লিখুন",
  "PLEASE_TYPE_EMAIL": "অনুগ্রহ করে ইমেইল লিখুন",
  "PLEASE_TYPE_PHONE_NUMBER": "অনুগ্রহ করে ফোন নম্বর লিখুন",
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": "ছবির আকার ২ এমবি এর কম হতে হবে",
  "SOMETHING_WRONG": "কিছু ভুল হয়েছে",
  "PROFILE_UPDATE_SUCCESSFULLY": "প্রোফাইল সফলভাবে আপডেট হয়েছে",
  "PASSWORD_UPDATE_SUCCESSFULLY": "পাসওয়ার্ড সফলভাবে আপডেট হয়েছে",
  "PLEASE_ENTER_VALID_INPUT": "অনুগ্রহ করে সঠিক ইনপুট দিন",
  "Verify Email": "ইমেইল যাচাই করুন",
  "Verify Number": "ফোন নম্বর যাচাই করুন",
  "Enter OTP": "ওটিপি দিন",
  "If you didn't receive a code!": "যদি কোড না পেয়ে থাকেন!",
  " Resend": " পুনরায় পাঠান",
  "Verify": "যাচাই করুন",
  "Back to sign in": "সাইন ইন পেইজে ফিরে যান",
  "Get OTP": "ওটিপি নিন",
  "Reset Password": "পাসওয়ার্ড রিসেট করুন",
  "Password Not Matched": "পাসওয়ার্ড মিলেনি",
  "Submit": "জমা দিন",
  "Popular Brands": "জনপ্রিয় ব্র্যান্ড",
  "Explore All Products": "সব পণ্য ঘুরে দেখুন",
  "Empty Wishlist": "ইচ্ছেতালিকা খালি",
  "Search": "অনুসন্ধান করুন",
  "Product added to cart": "পণ্যটি কার্টে যোগ করা হয়েছে",
  "Product Details": "পণ্যের বিবরণ",
  "No Review": "কোনো রিভিউ নেই",
  "No Shipping & Return Policy": "ডেলিভারি ও রিটার্ন নীতি নেই",
  "VIDEOS": "ভিডিও",
  "Product Videos": "পণ্যের ভিডিও",
  "Shipping & Return": "ডেলিভারি ও রিটার্ন",
  "Product Reviews": "পণ্যের রিভিউ",
  "Order Details": "অর্ডারের বিবরণ",
  "Thank You": "ধন্যবাদ",
  "Your Order status is as follows": "আপনার অর্ডারের স্ট্যাটাস নিচে দেওয়া হলো",
  "Order ID: ": "অর্ডার আইডি: ",
  "Order Canceled": "অর্ডার বাতিল হয়েছে",
  "Order Rejected": "অর্ডার বাতিল করা হয়েছে",
  "Order ID:": "অর্ডার আইডি:",
  "Order Date:": "অর্ডারের তারিখ:",
  "Order Status:": "অর্ডারের স্ট্যাটাস:",
  "Payment Status:": "পেমেন্ট স্ট্যাটাস:",
  "Payment Type:": "পেমেন্ট পদ্ধতি:",
  "Pending": "মুলতুবি",
  "Confirmed": "নিশ্চিত",
  "On The Way": "পথে আছে",
  "Delivered": "ডেলিভার করা হয়েছে",
  "Cenceled": "বাতিল",
  "Rejected": "প্রত্যাখ্যাত",
  "Paid": "পরিশোধিত",
  "Unpaid": "অপরিশোধিত",
  "Name:": "নাম:",
  "Phone:": "ফোন:",
  "Email:": "ইমেইল:",
  "Outlet Address:": "আউটলেটের ঠিকানা:",
  "Shipping Address:": "ডেলিভারির ঠিকানা:",
  "Billing Address:": "বিলিং ঠিকানা:",
  "Order Summary": "অর্ডার সারাংশ",
  "Subtotal": "সাবটোটাল",
  "Tax": "কর",
  "Shipping Charge": "ডেলিভারি চার্জ",
  "Discount": "ছাড়",
  "Download Receipt": "রসিদ ডাউনলোড করুন",
  "Return Request": "রিটার্ন অনুরোধ",
  "Cancel Order": "অর্ডার বাতিল করুন",
  "Tel:": "টেল:",
  "Order#": "অর্ডার#",
  "Qty": "পরিমাণ",
  "Item Description": "পণ্যের বিবরণ",
  "Price": "মূল্য",
  "Total": "মোট",
  "Order Type": "অর্ডারের ধরণ",
  "Order Date Time": "অর্ডারের তারিখ ও সময়",
  "Delivery": "ডেলিভারি",
  "Pickup": "পিকআপ",
  "POS": "POS",
  "Customer": "ক্রেতা",
  "Powered by": "চালিত",
  "Print Invoice": "চালান প্রিন্ট করুন",
  "Edit Review": "রিভিউ সম্পাদনা করুন",
  "Your Review": "আপনার রিভিউ",
  "Review Details": "রিভিউ বিবরণ",
  "Please write review details": "অনুগ্রহ করে রিভিউ বিস্তারিত লিখুন",
  "Upload Images": "ছবি আপলোড করুন",
  "Add Image": "ছবি যোগ করুন",
  "Submit Review": "রিভিউ জমা দিন",
  "Info: ": "তথ্য:",
  "Product": "পণ্য",
  "Delivery Status: ": "ডেলিভারি স্ট্যাটাস:",
  "Payment Status: ": "পেমেন্ট স্ট্যাটাস:",
  "Total: ": "মোট:",
  "Qty:": "পরিমাণ:",
  "Write Review": "রিভিউ লিখুন",
  "Price: ": "মূল্য:",
  "Return Status: ": "রিটার্ন স্ট্যাটাস:",
  "Accepted": "গৃহীত",
  "Return Order Details": "রিটার্ন অর্ডার বিবরণ",
  "Return Reason": "রিটার্নের কারণ",
  "Return Note": "রিটার্ন নোট",
  "Attachment": "সংযুক্তি",
  "Return Response": "রিটার্নের প্রতিক্রিয়া",
  "Request Return": "রিটার্ন অনুরোধ করুন",
  "Please select return reason": "অনুগ্রহ করে রিটার্নের কারণ নির্বাচন করুন",
  "Please write return note": "অনুগ্রহ করে রিটার্ন নোট লিখুন",
  "Please select an item": "অনুগ্রহ করে একটি পণ্য নির্বাচন করুন",
  "Order Canceled Successfully!": "অর্ডার সফলভাবে বাতিল হয়েছে!",
  "Return request submitted successfully!":
      "রিটার্ন অনুরোধ সফলভাবে জমা হয়েছে!",
  "Return request not submitted": "রিটার্ন অনুরোধ জমা হয়নি",
  "Review submitted successfully!": "রিভিউ সফলভাবে জমা হয়েছে!",
  "Review not submitted": "রিভিউ জমা হয়নি",
  "Review Updated successfully!": "রিভিউ সফলভাবে আপডেট হয়েছে!",
  "Address Added Successfully!": "ঠিকানা সফলভাবে যোগ হয়েছে!",
  "ADDRESS_UPDATED_SUCCESSFULLY": "ঠিকানা সফলভাবে আপডেট হয়েছে!",
  "ADDRESS_DELETED_SUCCESSFULLY": "ঠিকানা সফলভাবে মুছে ফেলা হয়েছে!",
  "Shipping Information": "ডেলিভারি তথ্য",
  "Pick Up": "পিক আপ",
  "Shipping Address": "ডেলিভারির ঠিকানা",
  "Edit": "সম্পাদনা করুন",
  "Add": "যোগ করুন",
  "Save shipping address as a billing address.":
      "ডেলিভারির ঠিকানাকে বিলিং ঠিকানা হিসেবে সংরক্ষণ করুন।",
  "Apply Promo, Coupon or Voucher": "প্রোমো, কুপন বা ভাউচার প্রয়োগ করুন",
  "Coupon Applied": "কুপন প্রয়োগ হয়েছে",
  "Get discount with your order": "আপনার অর্ডারের সাথে ছাড় পান",
  "You saved": "আপনি সঞ্চয় করেছেন",
  "Shipping & billing addresses are required.":
      "ডেলিভারি ও বিলিং ঠিকানা আবশ্যক।",
  "Outlet is required.": "আউটলেট নির্বাচন আবশ্যক।",
  "Save & Pay": "সংরক্ষণ করুন ও পেমেন্ট করুন",
  "Order": "অর্ডার",
  "On the": "পথে",
  "Way": "আছে",
  "Stock is over": "স্টক শেষ",
  "Shopping Cart": "শপিং কার্ট",
  "Your cart is empty": "আপনার কার্ট খালি",
  "Proceed to Checkout": "চেকআউটে যান",
  "Shipping, Taxes & Discount Calculate at Checkout":
      "ডেলিভারি, ট্যাক্স ও ছাড় চেকআউটে হিসাব করা হবে",
  "Remove": "মুছে ফেলুন",
  "Enter Code": "কোড লিখুন",
  "Please enter a valid coupon": "সঠিক কুপন কোড লিখুন",
  "Promo, Coupon or Voucher": "প্রোমো, কুপন বা ভাউচার",
  "Apply": "প্রয়োগ করুন",
  "Coupon & Vouchers for you": "আপনার জন্য কুপন ও ভাউচার",
  "Filter & Sorting": "ফিল্টার ও সাজান",
  "Product Type": "পণ্যের ধরণ",
  "Size": "সাইজ",
  "Color": "রঙ",
  "Brands": "ব্র্যান্ড",
  "Sort By": "সাজান",
  "Newest": "সর্বশেষ",
  "Price Low To High": "দাম কম থেকে বেশি",
  "Price High To Low": "দাম বেশি থেকে কম",
  "Top Rated": "শীর্ষ রেটিং",
  "See All": "সব দেখুন",
  "Payment Information": "পেমেন্ট তথ্য",
  "Select Payment Method": "পেমেন্ট পদ্ধতি নির্বাচন করুন",
  "Confirm Order": "অর্ডার নিশ্চিত করুন",
  "Products Found": "পণ্য পাওয়া গেছে",
  "Flash Sale": "ফ্ল্যাশ সেল",
  "New": "নতুন",
  "Reviews": "রিভিউ",
  " Products Found": "টি পণ্য পাওয়া গেছে",
  "Validation Error.": "ভ্যালিডেশন ত্রুটি।",
  "Credentials errors.": "ক্রেডেনশিয়াল ত্রুটি।",
  "Invalid credentials or you are blocked": "ভুল তথ্য বা আপনি ব্লকড",
  "Role errors.": "ভূমিকা সংক্রান্ত ত্রুটি।",
  "Role does not exist.": "এই ভূমিকা বিদ্যমান নেই।",
  "Login Successfully.": "সফলভাবে লগইন হয়েছে।",
  "Logged Out Successfully.": "সফলভাবে লগআউট হয়েছে।",
  "Invalid Api Key.": "ভুল API কী।",
  "User not match.": "ব্যবহারকারী মেলেনি।",
  "Something wrong.": "কিছু ভুল হয়েছে।",
  "The permission is denied.": "অনুমতি বাতিল করা হয়েছে।",
  "Product not match.": "পণ্য মেলেনি।",
  "The product already added in another offer. When the offer is end then you can add this item again.":
      "পণ্যটি ইতোমধ্যে অন্য একটি অফারে যুক্ত আছে। অফার শেষ হলে আপনি আবার এটি যোগ করতে পারবেন।",
  "The minimum order amount is ": "ন্যূনতম অর্ডার পরিমাণ হলো ",
  "The coupon time is expired": "কুপনের সময়সীমা শেষ হয়েছে",
  "The coupon does not exist": "এই কুপন বিদ্যমান নেই",
  "The code is invalid.": "কোডটি ভুল।",
  "The code is expired.": "কোডের মেয়াদ শেষ হয়েছে।",
  "Now you can reset your password.": "এখন আপনি পাসওয়ার্ড রিসেট করতে পারেন।",
  "Please check your email for the code.":
      "অনুগ্রহ করে কোডের জন্য আপনার ইমেইল চেক করুন।",
  "Please check your phone for the code.":
      "অনুগ্রহ করে কোডের জন্য আপনার ফোন চেক করুন।",
  "The token created fail.": "টোকেন তৈরি ব্যর্থ হয়েছে।",
  "This email does not exist.": "এই ইমেইলটি বিদ্যমান নয়।",
  "This phone does not exist.": "এই ফোন নম্বরটি বিদ্যমান নয়।",
  "This User does not exist.": "এই ব্যবহারকারী বিদ্যমান নয়।",
  "This phone already exist.": "এই ফোন নম্বরটি ইতোমধ্যে ব্যবহৃত হয়েছে।",
  "The OTP verify is successfully.": "ওটিপি সফলভাবে যাচাই হয়েছে।",
  "The User verify is successfully.": "ব্যবহারকারী সফলভাবে যাচাই হয়েছে।",
  "Register Successfully.": "সফলভাবে নিবন্ধিত হয়েছে।",
  "Your password reset Successfully.": "আপনার পাসওয়ার্ড সফলভাবে রিসেট হয়েছে।",
  "Select your payment method": "আপনার পেমেন্ট পদ্ধতি নির্বাচন করুন",
  "Your payment has been successfully processed":
      "আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে",
  "The payment is canceled": "পেমেন্ট বাতিল করা হয়েছে",
  "The payment gateway is disable": "পেমেন্ট গেটওয়ে নিষ্ক্রিয় রয়েছে",
  "The token saved successfully.": "টোকেন সফলভাবে সংরক্ষিত হয়েছে।",
  "The token is invalid.": "টোকেনটি ভুল।",
  "The order already accepted.": "অর্ডারটি ইতোমধ্যে গৃহীত হয়েছে।",
  "The order already confirmed.": "অর্ডারটি ইতোমধ্যে নিশ্চিত হয়েছে।",
  "This feature is disabled for the demo.": "ডেমোতে এই ফিচারটি বন্ধ আছে।",
  "Time slots already exist.": "টাইম স্লট ইতোমধ্যে বিদ্যমান।",
  "This attribute is invalid. Create attribute or attribute option.":
      "এই অ্যাট্রিবিউটটি সঠিক নয়। একটি অ্যাট্রিবিউট বা অপশন তৈরি করুন।",
  "This price amount provide invalid.": "প্রদত্ত মূল্যের পরিমাণ সঠিক নয়।",
  "This product attribute id provide invalid.":
      "প্রদত্ত প্রোডাক্ট অ্যাট্রিবিউট আইডি সঠিক নয়।",
  "This product attribute option id provide invalid.":
      "প্রদত্ত প্রোডাক্ট অ্যাট্রিবিউট অপশন আইডি সঠিক নয়।",
  "The sku has already been taken.": "এই SKU ইতোমধ্যে নেওয়া হয়েছে।",
  "Cannot remove this resource permanently. It is related with another resource.":
      "এই রিসোর্সটি স্থায়ীভাবে মুছে ফেলা যাবে না। এটি অন্য একটি রিসোর্সের সাথে সম্পর্কিত।",
  "The sku field is required.": "SKU ফিল্ডটি আবশ্যক।",
  "The email or phone field is required.": "ইমেইল অথবা ফোন নম্বর ফিল্ড আবশ্যক।",
  "The Country has already been taken.": "দেশ ইতোমধ্যে যুক্ত করা হয়েছে।",
  "The tax field is required for all products.":
      "সব পণ্যের জন্য কর ফিল্ড আবশ্যক।",
  "The quantity field is required for all products.":
      "সব পণ্যের জন্য পরিমাণ ফিল্ড আবশ্যক।",
  "The product filed is required.": "পণ্যের তথ্য আবশ্যক।",
  "The unit cost filed is required for all products.":
      "সব পণ্যের জন্য ইউনিট কস্ট ফিল্ড আবশ্যক।",
  "The total product unit cost is invalid.": "মোট ইউনিট কস্ট সঠিক নয়।",
  "The supplier is invalid.": "সরবরাহকারী সঠিক নয়।",
  "The status is invalid.": "স্ট্যাটাস সঠিক নয়।",
  "The Return request already exist.": "রিটার্ন অনুরোধ ইতোমধ্যে বিদ্যমান।",
  "The last outlet can not be delete": "শেষ আউটলেটটি মুছে ফেলা যাবে না",
  "Email Send Successfully.": "ইমেইল সফলভাবে পাঠানো হয়েছে।",
  "The amount is invalid.": "পরিমাণ সঠিক নয়।",
  "Available:": "উপলব্ধ:",
  "Piece": "পিস",
  "Search Results": "অনুসন্ধানের ফলাফল",
  "Order Type:": "অর্ডারের ধরন:",
  "Product Description": "পণ্যের বিবরণ",
  "Outlet": "আউটলেট",
  "Enter Valid Email Address": "বৈধ ইমেইল ঠিকানা লিখুন",
  "Thank you for your order!": "আপনার অর্ডারের জন্য ধন্যবাদ!",
  "Your order is confirmed.": "আপনার অর্ডার নিশ্চিত হয়েছে।",
  "Go to order details": "অর্ডার বিস্তারিত দেখুন",
  "YOUR_PAYMENT_HAS_BEEN_CONFIRMED": "আপনার পেমেন্ট নিশ্চিত হয়েছে",
  "PAYMENT_FAILED": "পেমেন্ট ব্যর্থ হয়েছে",
  "ARE_YOU_SURE_WANT_TO_CLOSE_THIS_PAYMENT_SESSION":
      "আপনি কি নিশ্চিতভাবে এই পেমেন্ট সেশন বন্ধ করতে চান?",
  "YES_CLOSE": "হ্যাঁ, বন্ধ করুন",
  "RETRY": "পুনরায় চেষ্টা করুন",
  "Please select payment method.": "অনুগ্রহ করে পেমেন্ট পদ্ধতি নির্বাচন করুন।",
  "Billing Address": "বিলিং ঠিকানা",
  "Insufficient balance": "অপর্যাপ্ত ব্যালেন্স",
  "Most Popular": "সবচেয়ে জনপ্রিয়",
  "Added to Wishlist": "উইশলিস্টে যুক্ত হয়েছে",
  "Removed from Wishlist": "উইশলিস্ট থেকে সরানো হয়েছে",
  "DELETE_ACCOUNT": "অ্যাকাউন্ট মুছুন",
  "COUNTRY": "দেশ",
  "STATE": "রাজ্য",
  "CITY": "শহর",
  "MAXIMUM_PURCHASE_QUANTITY_LIMIT_EXCEEDED":
      "সর্বোচ্চ ক্রয় পরিমাণ সীমা অতিক্রম করেছে",
  "YOU_ALREADY_ADDED_THE_MAXIMUM_QUANTITY":
      "আপনি ইতোমধ্যে সর্বোচ্চ পরিমাণ যোগ করেছেন",
  "COUNTRY_IS_REQUIRED": "দেশ আবশ্যক",
  "STATE_IS_REQUIRED": "রাজ্য আবশ্যক",
  "CITY_IS_REQUIRED": "শহর আবশ্যক",
  "PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS":
      "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
  "PASSWORD_IS_REQUIRED": "পাসওয়ার্ড আবশ্যক",
  "ENTER_A_VALID_EMAIL": "একটি বৈধ ইমেইল লিখুন",
  "EMAIL_IS_REQUIRED": "ইমেইল আবশ্যক",
  "ADDRESS_IS_REQUIRED": "ঠিকানা আবশ্যক",
  "OTP_IS_REQUIRED": "ওটিপি আবশ্যক",
  "PHONE_IS_REQUIRED": "ফোন নম্বর আবশ্যক",
  "NAME_IS_REQUIRED": "নাম আবশ্যক",
  "FULL_NAME_IS_REQUIRED": "পূর্ণ নাম আবশ্যক",
  "ORDER_HISTORY_IS_EMPTY": "অর্ডার ইতিহাস খালি!",
  "RETURN_ORDER_IS_EMPTY": "রিটার্ন অর্ডার খালি!",
  "WISHLIST_IS_EMPTY": "উইশলিস্ট খালি!",
  "CART_IS_EMPTY": "আপনার কার্ট খালি! এখনই কেনাকাটা শুরু করুন!",
  "NO_PRODUCT_FOUND": "কোনো পণ্য পাওয়া যায়নি!",
  "NO_SUB_CATEGORY_FOUND": "কোনো সাব-ক্যাটাগরি পাওয়া যায়নি!",
  "INFO": "তথ্য",
};
